services:
  broker1:
    image: apache/kafka:latest
    container_name: broker1
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker1:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CLUSTER_ID: 'r4zt_wrqTRuT7W2NJsB_GA'

    volumes:
      - ./.volumes/kafka/data:/var/lib/kafka/data

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 10s
      retries: 5

    networks:
      - app-network

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui
    container_name: kafka-ui
    restart: always
    ports:
      - "8092:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=broker1:9092
      - DYNAMIC_CONFIG_ENABLED=true

    networks:
      - app-network

    depends_on: [ broker1 ]

networks:
  app-network: