spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
  application:
    name: orders-api
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.example.ordersapi

    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.apiconsumer

topic:
  name: sandbox