spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://database/${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  application:
    name: orders-api

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.example.ordersapi

topic:
  name: sandbox